site_name: Slope
site_url: https://slopedoc.github.io/site
repo_url: https://github.com/baptiste-genest/slope
repo_name: baptiste-genest/slope
theme:
  name: material
  logo: static/slope_icon_white.png
  favicon: static/slope_icon.png
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant.preview
    - navigation.expand
    - content.code.select
    - content.code.copy
  palette:
    primary:
      black
  font:
    text: Libertinus Math
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
    #  - stylesheets/no-collapse.css
  - stylesheets/typography.css

nav:
  - index.md
  - cmake.md
  - options.md
  - Workflow:
    - workflow/slide.md
    - workflow/transitions.md
      #    - workflow/full_example.md
  - Primitives:
    - Primitives/Animation.md
    - Screen Primitives:
      - Primitives/screen_primitives.md
      - Primitives/images.md
      - Primitives/Gifs.md
      - Latex:
        - Primitives/Latex/latex.md
        - Primitives/Latex/dynamic.md
        - Primitives/Latex/titles.md
      - Placement:
        - placement/absolute.md
        - placement/relative_placement.md
        - placement/persistant_placement.md
        - placement/tracking.md
    - Polyscope Primitives:
      - Primitives/polyscope_primitives.md
      - Primitives/transforms.md
      - Primitives/point_cloud.md
      - Primitives/Mesh.md
      - Primitives/camera.md
      - Primitives/quantities.md
  - limitations.md
  - about.md

